name: smoke-eda
on: [push, pull_request]
jobs:
  run-eda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import & CLI parse smoke
        run: |
          python - << "PY"
          import importlib.util
          spec = importlib.util.spec_from_file_location("eda", "src/eda_v1.0.py")
          mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
          print("OK: import & CLI available")
          PY
